using Forge.Cli.Config;
using Forge.Cli.Planning;
using Forge.Cli.Stubs;

namespace Forge.Cli.Templates;

/// <summary>
/// Everything a generator needs, resolved once. Parameters that belong to the whole run live
/// here rather than being threaded through every ITemplate method signature.
/// </summary>
public sealed class TemplateContext(
    ForgeConfig config,
    string solutionRoot,
    CodeStyle codeStyle,
    StubRepository stubs,
    bool force)
{
    private SourceIndex? _domainIndex;
    private SourceIndex? _infrastructureIndex;
    private SourceIndex? _applicationIndex;

    public ForgeConfig Config { get; } = config;
    public string SolutionRoot { get; } = solutionRoot;
    public CodeStyle CodeStyle { get; } = codeStyle;
    public StubRepository Stubs { get; } = stubs;
    public bool Force { get; } = force;

    /// <summary>Set by commands that can legitimately run before the entity type exists.</summary>
    public bool AllowMissingEntity { get; set; }

    /// <summary>Second key for --force: permits overwriting a file edited since generation.</summary>
    public bool OverwriteModified { get; set; }

    public GeneratedManifest Manifest { get; set; } = null!;

    /// <summary>
    /// The single existence guard every generator uses.
    ///
    /// --force alone overwrites only files whose content still matches what forge generated.
    /// A file a human has edited needs --overwrite-modified as well, so re-running a generator
    /// can never silently destroy someone's work.
    /// </summary>
    public GenerationPlan CreateOrSkip(string path, Func<string> content)
    {
        if (!File.Exists(path))
            return GenerationPlan.Of(new FileAction.Create(path, content()));

        if (!Force)
            return GenerationPlan.Of(new FileAction.Skip(path, "already exists (use --force to overwrite)"));

        if (Manifest is not null && !OverwriteModified && Manifest.IsModifiedSinceGeneration(path))
        {
            var reason = Manifest.Find(path) is null
                ? "exists but was not generated by forge; --force alone will not overwrite it " +
                  "(add --overwrite-modified)"
                : "has been edited since it was generated; --force alone will not overwrite it " +
                  "(add --overwrite-modified)";

            return GenerationPlan.Of(new FileAction.Skip(path, reason, Protected: true));
        }

        return GenerationPlan.Of(new FileAction.Create(path, content()));
    }

    /// <summary>
    /// Types declared in the domain project, built lazily. Used to verify an entity actually
    /// exists before generating code that references it.
    /// </summary>
    public SourceIndex DomainIndex =>
        _domainIndex ??= SourceIndex.Build(PathIn(Config.DomainProject));

    /// <summary>Types in the infrastructure project — used to locate the DbContext by name.</summary>
    public SourceIndex InfrastructureIndex =>
        _infrastructureIndex ??= SourceIndex.Build(PathIn(Config.InfrastructureProject));

    /// <summary>Types in the application project — used to resolve --returns to a real namespace.</summary>
    public SourceIndex ApplicationIndex =>
        _applicationIndex ??= SourceIndex.Build(PathIn(Config.ApplicationProject));

    /// <summary>Absolute path from a solution-root-relative path.</summary>
    public string PathIn(params string[] segments) =>
        Path.GetFullPath(Path.Combine(new[] { SolutionRoot }.Concat(segments).ToArray()));

    /// <summary>Path relative to the solution root, with forward slashes — the form used in output.</summary>
    public string Relative(string absolutePath) =>
        Path.GetRelativePath(SolutionRoot, absolutePath).Replace('\\', '/');

    /// <summary>Renders a stub and adapts it to the target project's code style.</summary>
    public string Render(string stubName, IReadOnlyDictionary<string, string> model) =>
        CodeStyleFormatter.Apply(Stubs.Render(stubName, model), CodeStyle);

    public string NullableMarker => CodeStyle.NullableEnabled ? "?" : string.Empty;

    public string Usings(params string[] namespaces) =>
        CodeStyleFormatter.UsingsFor(CodeStyle, namespaces);

    /// <summary>
    /// Usings for a generated file, resolved from the TYPES it references rather than guessed.
    ///
    /// Anything a generator emits with user-chosen property types needs this. A property of type
    /// OrderStatus compiles only if the enum's namespace is imported, and nothing else in the
    /// generated file brings it in — the enum lands in the domain's Enums namespace while the
    /// entity, the response and the message record land in three other namespaces. Reported from
    /// the field as "Book and BookResponse were generated without using Library.Domain.Enums".
    ///
    /// Resolution is by bare type name against the domain and application indexes, so it is
    /// purely syntactic. Generic and array types are deliberately not resolved: picking the
    /// namespace for List&lt;T&gt; means parsing the type argument, and guessing wrong emits a
    /// using for a type that is not there.
    /// </summary>
    public string UsingsForTypes(
        IEnumerable<string> typeNames,
        string targetNamespace,
        params string[] alwaysInclude)
    {
        var namespaces = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var ns in alwaysInclude) namespaces.Add(ns);

        foreach (var typeName in typeNames)
        {
            var bare = typeName.TrimEnd('?');

            var declaring = DomainIndex.Types.FirstOrDefault(t => t.Name == bare)
                            ?? ApplicationIndex.Types.FirstOrDefault(t => t.Name == bare);

            if (declaring?.Namespace is { Length: > 0 } ns && ns != targetNamespace)
            {
                namespaces.Add(ns);
            }
        }

        return Usings([.. namespaces]);
    }
}
