using Forge.Cli.Config;
using Forge.Cli.Planning;
using Forge.Cli.Stubs;
using Forge.Cli.Templates;
using Forge.Cli.Templates.OnionWolverineErrorOr;

namespace Forge.Cli.Tests;

/// <summary>
/// swagger:install — retrofitting an OpenAPI document onto a solution that already exists.
///
/// The upgrade case is the one that matters and the one that is easy to get wrong: every
/// solution forge scaffolded before Swagger was part of the template already calls
/// AddEndpointsApiExplorer(). Wiring both registrations under one idempotency marker would
/// either duplicate that call or skip AddSwaggerGen() entirely, depending on which way the check
/// was written — and both produce a solution that looks wired and is not.
/// </summary>
public class SwaggerInstallTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "forge-sw-" + Guid.NewGuid().ToString("N")[..8]);

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { /* best effort */ }
        GC.SuppressFinalize(this);
    }

    /// <summary>A solution forge scaffolded before Swagger existed: ApiExplorer, nothing else.</summary>
    private const string LegacyProgram = """
        using Microsoft.EntityFrameworkCore;

        var builder = WebApplication.CreateBuilder(args);

        builder.Services.AddControllers();
        builder.Services.AddEndpointsApiExplorer();
        builder.Services.AddInfrastructure();

        var app = builder.Build();

        app.UseHttpsRedirection();
        app.MapControllers();

        app.Run();
        """;

    private const string Csproj = """
        <Project Sdk="Microsoft.NET.Sdk.Web">
          <PropertyGroup>
            <TargetFramework>net8.0</TargetFramework>
          </PropertyGroup>

          <ItemGroup>
            <PackageReference Include="WolverineFx" Version="3.0.0" />
          </ItemGroup>
        </Project>
        """;

    private void Scaffold(string program = LegacyProgram)
    {
        var api = Path.Combine(_root, "src", "App.API");
        Directory.CreateDirectory(api);

        File.WriteAllText(Path.Combine(api, "App.API.csproj"), Csproj);
        File.WriteAllText(Path.Combine(api, "Program.cs"), program);

        File.WriteAllText(Path.Combine(_root, "forge.config.json"), """
            {
              "version": 1,
              "template": "onion-wolverine-erroror",
              "apiProject": "src/App.API"
            }
            """);
    }

    private PlanResult Plan(CodeStyle? style = null)
    {
        var loaded = ConfigLoader.Load(_root);
        Assert.True(loaded.Ok, loaded.Error);

        var ctx = new TemplateContext(
            loaded.Config!, loaded.SolutionRoot!, style ?? CodeStyle.Default,
            new StubRepository(loaded.SolutionRoot!, loaded.Config!.StubOverridesPath, "OnionWolverineErrorOr"),
            force: false);

        return SwaggerScaffold.Plan(ctx);
    }

    private static string PatchedText(PlanResult result, string endsWith) =>
        result.Plan.Actions.OfType<FileAction.Patch>()
            .Single(a => a.Path.EndsWith(endsWith, StringComparison.OrdinalIgnoreCase))
            .After;

    private void Apply(PlanResult result)
    {
        Assert.True(result.Ok, result.Error);
        var execution = new PlanExecutor().Apply(result.Plan);
        Assert.True(execution.Ok, execution.Error);
    }

    [Fact]
    public void It_adds_the_package_to_the_existing_item_group()
    {
        Scaffold();

        var csproj = PatchedText(Plan(), ".csproj");

        Assert.Contains(
            $"""<PackageReference Include="Swashbuckle.AspNetCore" Version="{SwaggerScaffold.Version}" />""",
            csproj);

        Assert.Contains("WolverineFx", csproj);
        Assert.Equal(1, csproj.Split("<ItemGroup>").Length - 1);
    }

    [Fact]
    public void It_wires_the_registration_and_the_middleware()
    {
        Scaffold();

        var program = PatchedText(Plan(), "Program.cs");

        Assert.Contains("builder.Services.AddSwaggerGen();", program);
        Assert.Contains("app.UseSwagger();", program);
        Assert.Contains("app.UseSwaggerUI();", program);
        Assert.Contains("app.Environment.IsDevelopment()", program);
    }

    /// <summary>
    /// The regression this class exists for. A solution generated by any earlier forge already
    /// has this call; adding a second one is a duplicate registration in the container.
    /// </summary>
    [Fact]
    public void It_does_not_duplicate_an_existing_ApiExplorer_registration()
    {
        Scaffold();

        var program = PatchedText(Plan(), "Program.cs");

        Assert.Equal(1, program.Split("AddEndpointsApiExplorer(").Length - 1);
        Assert.Contains("builder.Services.AddSwaggerGen();", program);
    }

    /// <summary>A brownfield API that never had ApiExplorer gets both halves.</summary>
    [Fact]
    public void It_adds_ApiExplorer_when_the_project_does_not_have_it()
    {
        Scaffold(LegacyProgram.Replace("builder.Services.AddEndpointsApiExplorer();\r\n", string.Empty)
                              .Replace("builder.Services.AddEndpointsApiExplorer();\n", string.Empty));

        var program = PatchedText(Plan(), "Program.cs");

        Assert.Equal(1, program.Split("AddEndpointsApiExplorer(").Length - 1);
        Assert.Equal(1, program.Split("AddSwaggerGen(").Length - 1);
    }

    /// <summary>
    /// Registration before the container closes, middleware after the host exists. Getting
    /// either side of Build() wrong compiles and then fails at startup.
    /// </summary>
    [Fact]
    public void Registration_lands_before_Build_and_middleware_after_it()
    {
        Scaffold();

        var program = PatchedText(Plan(), "Program.cs");

        var build = program.IndexOf("builder.Build()", StringComparison.Ordinal);
        var registration = program.IndexOf("AddSwaggerGen(", StringComparison.Ordinal);
        var middleware = program.IndexOf("app.UseSwagger();", StringComparison.Ordinal);
        var run = program.IndexOf("app.Run()", StringComparison.Ordinal);

        Assert.True(registration < build, "AddSwaggerGen must be registered before the host is built");
        Assert.True(middleware > build, "UseSwagger needs the built app");
        Assert.True(middleware < run, "UseSwagger must be registered before the host runs");
    }

    [Fact]
    public void Running_it_twice_changes_nothing()
    {
        Scaffold();

        Apply(Plan());
        var second = Plan();

        Assert.True(second.Ok, second.Error);
        Assert.True(second.Plan.IsEntirelySkipped,
            "a second swagger:install should be a no-op: " +
            string.Join(", ", second.Plan.Actions.Select(a => a.GetType().Name + " " + a.Path)));
    }

    /// <summary>
    /// A hand-wired solution is already done. forge must recognise that rather than adding a
    /// second copy of wiring the developer wrote themselves.
    /// </summary>
    [Fact]
    public void A_hand_wired_solution_is_recognised_as_already_done()
    {
        Scaffold(LegacyProgram
            .Replace("builder.Services.AddInfrastructure();",
                "builder.Services.AddInfrastructure();\nbuilder.Services.AddSwaggerGen();")
            .Replace("app.UseHttpsRedirection();",
                "app.UseSwagger();\napp.UseSwaggerUI();\napp.UseHttpsRedirection();"));

        var result = Plan();

        Assert.True(result.Ok, result.Error);
        Assert.DoesNotContain(result.Plan.Actions.OfType<FileAction.Patch>(),
            a => a.Path.EndsWith("Program.cs", StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Minimal-API shape: no MapControllers, no UseHttpsRedirection. The anchor chain has to
    /// fall through to app.Run() rather than giving up — this is what a non-forge solution
    /// adopting forge actually looks like.
    /// </summary>
    [Fact]
    public void It_falls_back_to_app_Run_when_the_usual_anchors_are_absent()
    {
        Scaffold("""
            var builder = WebApplication.CreateBuilder(args);

            builder.Services.AddControllers();

            var app = builder.Build();

            app.MapGet("/", () => "ok");

            app.Run();
            """);

        var program = PatchedText(Plan(), "Program.cs");

        var middleware = program.IndexOf("app.UseSwagger();", StringComparison.Ordinal);
        var run = program.IndexOf("app.Run()", StringComparison.Ordinal);

        Assert.True(middleware > 0, "the middleware should still be placed");
        Assert.True(middleware < run, "and it must come before app.Run()");
    }

    /// <summary>
    /// A Program.cs with no host at all cannot be patched. The error has to name the file and
    /// say what to do, not "anchor not found".
    /// </summary>
    [Fact]
    public void An_unpatchable_program_fails_with_a_useful_message()
    {
        Scaffold("var x = 1;\n");

        var result = Plan();

        Assert.False(result.Ok);
        Assert.Equal(Forge.Cli.Cli.ExitCodes.AnchorNotFound, result.ExitCode);
        Assert.Contains("Program.cs", result.Error);
    }

    /// <summary>
    /// Implicit usings cover both namespaces in a Web SDK project, so adding them there is
    /// noise. A project with the flag off genuinely needs them.
    /// </summary>
    [Fact]
    public void Usings_are_added_only_when_implicit_usings_are_off()
    {
        Scaffold();
        var withImplicit = PatchedText(Plan(CodeStyle.Default with { ImplicitUsings = true }), "Program.cs");
        Assert.DoesNotContain("using Microsoft.AspNetCore.Builder;", withImplicit);

        Dispose();
        Directory.CreateDirectory(_root);
        Scaffold();
        var withoutImplicit = PatchedText(Plan(CodeStyle.Default with { ImplicitUsings = false }), "Program.cs");
        Assert.Contains("using Microsoft.AspNetCore.Builder;", withoutImplicit);
    }
}
